<?php

namespace LSB\AppBundle\Repository;

/**
 * BoardGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoardGameRepository extends \Doctrine\ORM\EntityRepository
{
}
