<?php

namespace LSB\AppBundle\Repository;

/**
 * MeetingDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetingDateRepository extends \Doctrine\ORM\EntityRepository
{
}
