<?php

namespace LSB\AppBundle\Repository;

/**
 * WarhammerBattleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarhammerBattleRepository extends \Doctrine\ORM\EntityRepository
{
}
