<?php

namespace LSB\AppBundle\Repository;

/**
 * Warhammer40kRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Warhammer40kRepository extends \Doctrine\ORM\EntityRepository
{
}
