lsb_app_homepage:
    path:     /
    defaults: { _controller: LSBAppBundle:App:index }

lsb_app_lobby:
    path:     /{timestamp}
    defaults: { _controller: LSBAppBundle:App:lobby }
    requirements:
        timestamp: \d+

lsb_app_adminpage:
    path:     /admin
    defaults: { _controller: LSBAppBundle:Admin:index }

lsb_app_user_management:
    path:     /admin/gestion-des-utilisateurs
    defaults: { _controller: LSBAppBundle:Admin:userManagement }

lsb_app_user_delete:
    path:     /admin/gestion-des-utilisateurs/supprimer/{id}
    defaults: { _controller: LSBAppBundle:Admin:delete }
    requirements:
        id:   \d+

lsb_app_user_promote:
    path:     /admin/gestion-des-utilisateurs/promouvoir/{id}
    defaults: { _controller: LSBAppBundle:Admin:promote }
    requirements:
        id:   \d+

lsb_app_user_demote:
    path:     /admin/gestion-des-utilisateurs/retrograder/{id}
    defaults: { _controller: LSBAppBundle:Admin:demote }
    requirements:
        id:   \d+