lsb_app_homepage:
    path:     /
    defaults: { _controller: LSBAppBundle:App:index }

lsb_app_tournament:
    path:     /tournoi
    defaults: { _controller: LSBAppBundle:App:tournament }

lsb_app_lobby:
    path:     /salon/{timestamp}
    defaults: { _controller: LSBAppBundle:App:lobby }
    requirements:
        timestamp: \d+

lsb_app_creation_warhammer40k:
    path:     /salon/warhammer-40k/{timestamp}
    defaults: { _controller: LSBAppBundle:App:warhammer40kCreation }
    requirements:
        timestamp: \d+

lsb_app_creation_warhammerbattle:
    path:     /salon/warhammer-battle/{timestamp}
    defaults: { _controller: LSBAppBundle:App:warhammerbattleCreation }
    requirements:
        timestamp: \d+

lsb_app_creation_boardgame:
    path:     /salon/jeu-de-plateau/{timestamp}
    defaults: { _controller: LSBAppBundle:App:boardgameCreation }
    requirements:
        timestamp: \d+

lsb_app_join_warhammer40k:
    path: /join-warhammer40k/{timestamp}{id}
    defaults: { _controller: LSBAppBundle:ManagementGame:joinWarhammer40k }
    requirements:
        timestamp:  \d+
        id:         \d+

lsb_app_leave_warhammer40k:
    path: /leave-warhammer40k/{timestamp}{id}
    defaults: { _controller: LSBAppBundle:ManagementGame:leaveWarhammer40k }
    requirements:
        timestamp:  \d+
        id:         \d+

lsb_app_delete_warhammer40k:
    path: /delete-warhammer40k/{timestamp}{id}
    defaults: { _controller: LSBAppBundle:ManagementGame:deleteWarhammer40k }
    requirements:
        timestamp:  \d+
        id:         \d+

lsb_app_join_warhammerbattle:
    path: /join-warhammerbattle/{timestamp}{id}
    defaults: { _controller: LSBAppBundle:ManagementGame:joinWarhammerbattle }
    requirements:
        timestamp:  \d+
        id:         \d+

lsb_app_leave_warhammerbattle:
    path: /leave-warhammerbattle/{timestamp}{id}
    defaults: { _controller: LSBAppBundle:ManagementGame:leaveWarhammerbattle }
    requirements:
        timestamp:  \d+
        id:         \d+

lsb_app_delete_warhammerbattle:
    path: /delete-warhammerbattle/{timestamp}{id}
    defaults: { _controller: LSBAppBundle:ManagementGame:deleteWarhammerbattle }
    requirements:
        timestamp:  \d+
        id:         \d+

lsb_app_join_boardgame:
    path: /join-boardgame/{timestamp}{id}
    defaults: { _controller: LSBAppBundle:ManagementGame:joinBoardgame }
    requirements:
        timestamp:  \d+
        id:         \d+

lsb_app_leave_boardgame:
    path: /leave-boardgame/{timestamp}{id}
    defaults: { _controller: LSBAppBundle:ManagementGame:leaveBoardgame }
    requirements:
        timestamp:  \d+
        id:         \d+

lsb_app_delete_boardgame:
    path: /delete-boardgame/{timestamp}{id}
    defaults: { _controller: LSBAppBundle:ManagementGame:deleteBoardgame }
    requirements:
        timestamp:  \d+
        id:         \d+

lsb_app_legal_notice:
    path: /mentions-legales
    defaults: { _controller: LSBAppBundle:App:legalNotice }

lsb_app_adminpage:
    path:     /admin
    defaults: { _controller: LSBAppBundle:Admin:index }

lsb_app_user_management:
    path:     /admin/gestion-des-utilisateurs
    defaults: { _controller: LSBAppBundle:Admin:userManagement }

lsb_app_user_delete:
    path:     /admin/gestion-des-utilisateurs/supprimer/{id}
    defaults: { _controller: LSBAppBundle:Admin:delete }
    requirements:
        id:   \d+

lsb_app_user_promote:
    path:     /admin/gestion-des-utilisateurs/promouvoir/{id}
    defaults: { _controller: LSBAppBundle:Admin:promote }
    requirements:
        id:   \d+

lsb_app_user_demote:
    path:     /admin/gestion-des-utilisateurs/retrograder/{id}
    defaults: { _controller: LSBAppBundle:Admin:demote }
    requirements:
        id:   \d+