services:
    lsb_app.generatedates:
        class: LSB\AppBundle\Date\LSBGenerateDates

    lsb_app.datefr.twig_extension:
        class: LSB\AppBundle\Twig\DateFrExtension
        tags:
            - { name: twig.extension }

    lsb_app.sortusers:
        class: LSB\AppBundle\UserManagement\LSBSortUsers